/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_daviddiaz;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bG_Lugar = new javax.swing.ButtonGroup();
        jD_Restaurante = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCB_Categoria_Res = new javax.swing.JComboBox<>();
        jCB_Calificacion_Res = new javax.swing.JComboBox<>();
        jB_Guardar_res = new javax.swing.JButton();
        jD_Cancha = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCB_Categoria_Can = new javax.swing.JComboBox<>();
        jTF_Estado = new javax.swing.JTextField();
        jB_Guardar_Can = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPOPM_MENU = new javax.swing.JPopupMenu();
        jM_Eliminar = new javax.swing.JMenuItem();
        jTP_Principal = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTF_Nombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTA_Direccion = new javax.swing.JTextArea();
        jTF_Nivel_Seguridad = new javax.swing.JTextField();
        jRB_Cancha = new javax.swing.JRadioButton();
        jRB_Restaurante = new javax.swing.JRadioButton();
        jRB_Casa = new javax.swing.JRadioButton();
        jB_Guardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTF_Nombre_Carre = new javax.swing.JTextField();
        jTF_Numero_Carre = new javax.swing.JTextField();
        jTF_Distancia_Carre = new javax.swing.JTextField();
        jCB_Lugar_Inicio = new javax.swing.JComboBox<>();
        jCB_Lugar_Final = new javax.swing.JComboBox<>();
        jB_Guardar_Carre = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT_Listar = new javax.swing.JTable();
        jB_R = new javax.swing.JButton();
        jB_C = new javax.swing.JButton();
        jB_Ca = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jT_Categoria = new javax.swing.JTree();
        jB_T_Restaurantes = new javax.swing.JButton();
        jB_T_Canchas = new javax.swing.JButton();

        jLabel5.setText("Categoria:");

        jLabel6.setText("Calificacion:");

        jCB_Categoria_Res.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chino", "Mexicano", "Italiano", "Comida Rapida" }));

        jCB_Calificacion_Res.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", " " }));

        jB_Guardar_res.setText("Guardar");
        jB_Guardar_res.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Guardar_resMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jD_RestauranteLayout = new javax.swing.GroupLayout(jD_Restaurante.getContentPane());
        jD_Restaurante.getContentPane().setLayout(jD_RestauranteLayout);
        jD_RestauranteLayout.setHorizontalGroup(
            jD_RestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_RestauranteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jD_RestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jD_RestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCB_Categoria_Res, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB_Calificacion_Res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Guardar_res, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jD_RestauranteLayout.setVerticalGroup(
            jD_RestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_RestauranteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jD_RestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCB_Categoria_Res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(jD_RestauranteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCB_Calificacion_Res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jB_Guardar_res)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jLabel7.setText("Categoria:");

        jLabel8.setText("Estado:");

        jCB_Categoria_Can.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Football", "Basquetball", "Tennis" }));

        jTF_Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_EstadoActionPerformed(evt);
            }
        });

        jB_Guardar_Can.setText("Guardar");
        jB_Guardar_Can.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Guardar_CanMouseClicked(evt);
            }
        });
        jB_Guardar_Can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Guardar_CanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jD_CanchaLayout = new javax.swing.GroupLayout(jD_Cancha.getContentPane());
        jD_Cancha.getContentPane().setLayout(jD_CanchaLayout);
        jD_CanchaLayout.setHorizontalGroup(
            jD_CanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_CanchaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jD_CanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jD_CanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jD_CanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCB_Categoria_Can, 0, 99, Short.MAX_VALUE)
                        .addComponent(jTF_Estado))
                    .addComponent(jB_Guardar_Can, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jD_CanchaLayout.setVerticalGroup(
            jD_CanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jD_CanchaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jD_CanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCB_Categoria_Can, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jD_CanchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTF_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(jB_Guardar_Can)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jButton2.setText("jButton2");

        jM_Eliminar.setText("Eliminar");
        jM_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_EliminarActionPerformed(evt);
            }
        });
        jPOPM_MENU.add(jM_Eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTP_Principal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTP_PrincipalStateChanged(evt);
            }
        });

        jLabel1.setText("Nombre: ");

        jLabel2.setText("Direccion:");

        jLabel3.setText("Nivel de Seguridad:");

        jLabel4.setText("Tipo de Lugar:");

        jTA_Direccion.setColumns(20);
        jTA_Direccion.setRows(5);
        jScrollPane1.setViewportView(jTA_Direccion);

        bG_Lugar.add(jRB_Cancha);
        jRB_Cancha.setText("Cancha");
        jRB_Cancha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB_CanchaActionPerformed(evt);
            }
        });

        bG_Lugar.add(jRB_Restaurante);
        jRB_Restaurante.setSelected(true);
        jRB_Restaurante.setText("Restaurante");

        bG_Lugar.add(jRB_Casa);
        jRB_Casa.setText("Casa");

        jB_Guardar.setText("Guardar");
        jB_Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_GuardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_Nivel_Seguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRB_Cancha)
                            .addComponent(jRB_Restaurante)
                            .addComponent(jRB_Casa))))
                .addGap(28, 28, 28)
                .addComponent(jB_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTF_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTF_Nivel_Seguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jRB_Restaurante)))
                    .addComponent(jB_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jRB_Cancha)
                .addGap(18, 18, 18)
                .addComponent(jRB_Casa)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        jTP_Principal.addTab("Agregar Lugar", jPanel1);

        jLabel9.setText("Nombre:");

        jLabel10.setText("Numero:");

        jLabel11.setText("Distancia:");

        jLabel12.setText("Lugar Inicio:");

        jLabel13.setText("Lugar Final:");

        jTF_Nombre_Carre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_Nombre_CarreActionPerformed(evt);
            }
        });

        jTF_Distancia_Carre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_Distancia_CarreActionPerformed(evt);
            }
        });

        jB_Guardar_Carre.setText("Guardar");
        jB_Guardar_Carre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_Guardar_CarreMouseClicked(evt);
            }
        });
        jB_Guardar_Carre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Guardar_CarreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCB_Lugar_Final, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel11))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTF_Distancia_Carre, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTF_Numero_Carre, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTF_Nombre_Carre)
                                        .addComponent(jCB_Lugar_Inicio, 0, 165, Short.MAX_VALUE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jB_Guardar_Carre, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(367, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTF_Nombre_Carre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTF_Numero_Carre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTF_Distancia_Carre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jCB_Lugar_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jCB_Lugar_Final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_Guardar_Carre, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jTP_Principal.addTab("Agregar Carretera", jPanel2);

        jT_Listar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Dirección", "Nivel Seguridad", "Carretera Entrada", "Carretera Salida", "Categoria", "Calificación", "Estado", "Numero", "Distancia", "Lugar Inicio", "Lugar Final"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jT_Listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_ListarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jT_Listar);

        jB_R.setText("Restaurantes");
        jB_R.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_RMouseClicked(evt);
            }
        });
        jB_R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_RActionPerformed(evt);
            }
        });

        jB_C.setText("Canchas");
        jB_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_CMouseClicked(evt);
            }
        });

        jB_Ca.setText("Carreteras");
        jB_Ca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_CaMouseClicked(evt);
            }
        });
        jB_Ca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_CaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jB_R, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addComponent(jB_C, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(jB_Ca, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_R)
                    .addComponent(jB_C)
                    .addComponent(jB_Ca))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jTP_Principal.addTab("Listar", jPanel3);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Categoria");
        jT_Categoria.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(jT_Categoria);

        jB_T_Restaurantes.setText("Restaurantes");
        jB_T_Restaurantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_T_RestaurantesMouseClicked(evt);
            }
        });

        jB_T_Canchas.setText("Canchas");
        jB_T_Canchas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_T_CanchasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jB_T_Restaurantes, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jB_T_Canchas, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_T_Restaurantes)
                    .addComponent(jB_T_Canchas))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTP_Principal.addTab("Listar por Categoria", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTP_Principal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTP_Principal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRB_CanchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB_CanchaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB_CanchaActionPerformed

    private void jB_GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_GuardarMouseClicked
        try {
            String nombre, direccion;
            int nivel_se;
            nombre = jTF_Nombre.getText();
            direccion = jTA_Direccion.getText();
            nivel_se = Integer.parseInt(jTF_Nivel_Seguridad.getText());
            if (jRB_Restaurante.isSelected()) {
                jD_Restaurante.setModal(true);
                jD_Restaurante.pack();
                jD_Restaurante.setLocationRelativeTo(this);
                jD_Restaurante.setVisible(true);
                lugar.add(new Restaurante(categoria_res, calificacion, nombre, direccion, nivel_se, new Carretera(), new Carretera()));
            } else if (jRB_Cancha.isSelected()) {
                jD_Cancha.setModal(true);
                jD_Cancha.pack();
                jD_Cancha.setLocationRelativeTo(this);
                jD_Cancha.setVisible(true);
                lugar.add(new Canchas(categoria_can, estado, nombre, direccion, nivel_se, new Carretera(), new Carretera()));
            } else if (jRB_Casa.isSelected()) {
                lugar.add(new Casa(nombre, direccion, nivel_se, new Carretera(), new Carretera()));
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        }
        jTF_Nombre.setText("");
        jTA_Direccion.setText("");
        jTF_Nivel_Seguridad.setText("");
        jRB_Restaurante.setSelected(true);
        jRB_Cancha.setSelected(false);
        jRB_Casa.setSelected(false);


    }//GEN-LAST:event_jB_GuardarMouseClicked

    private void jTF_EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_EstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_EstadoActionPerformed

    private void jB_Guardar_CanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Guardar_CanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_Guardar_CanActionPerformed

    private void jB_Guardar_resMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Guardar_resMouseClicked
        try {
            categoria_res = jCB_Categoria_Res.getSelectedItem().toString();
            calificacion = Integer.parseInt(jCB_Calificacion_Res.getSelectedItem().toString());
            JOptionPane.showMessageDialog(this, "Lugar Guardado");
            jD_Restaurante.setModal(false);
            jD_Restaurante.setVisible(false);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        }
        jCB_Categoria_Res.setSelectedIndex(0);
        jCB_Calificacion_Res.setSelectedIndex(0);
    }//GEN-LAST:event_jB_Guardar_resMouseClicked

    private void jB_Guardar_CanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Guardar_CanMouseClicked
        try {
            categoria_can = jCB_Categoria_Can.getSelectedItem().toString();
            estado = jTF_Estado.getText();
            JOptionPane.showMessageDialog(this, "Lugar Guardado");
            jD_Cancha.setModal(false);
            jD_Cancha.setVisible(false);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        }
        jCB_Categoria_Can.setSelectedIndex(0);
        jTF_Estado.setText("");
    }//GEN-LAST:event_jB_Guardar_CanMouseClicked

    private void jTF_Nombre_CarreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_Nombre_CarreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_Nombre_CarreActionPerformed

    private void jTF_Distancia_CarreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_Distancia_CarreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_Distancia_CarreActionPerformed

    private void jTP_PrincipalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTP_PrincipalStateChanged
        if (jTP_Principal.getSelectedIndex() == 1) {
            DefaultComboBoxModel modelo = new DefaultComboBoxModel();
            DefaultComboBoxModel modelo_1 = new DefaultComboBoxModel();
            new DefaultComboBoxModel();
            for (Lugar temp : lugar) {
                modelo.addElement(temp);
            }
            for (Lugar temp : lugar) {
                modelo_1.addElement(temp);
            }
            jCB_Lugar_Inicio.setModel(modelo);
            jCB_Lugar_Final.setModel(modelo_1);
        }
    }//GEN-LAST:event_jTP_PrincipalStateChanged

    private void jB_Guardar_CarreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Guardar_CarreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_Guardar_CarreActionPerformed

    private void jB_Guardar_CarreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_Guardar_CarreMouseClicked
        try {
            String nombre;
            int numero;
            int distancia;
            int index, index_2;
            index = jCB_Lugar_Inicio.getSelectedIndex();
            index_2 = jCB_Lugar_Final.getSelectedIndex();
            nombre = jTF_Nombre_Carre.getText();
            numero = Integer.parseInt(jTF_Numero_Carre.getText());
            distancia = Integer.parseInt(jTF_Distancia_Carre.getText());
            carretera.add(new Carretera(nombre, numero, distancia, (Lugar) jCB_Lugar_Inicio.getSelectedItem(), (Lugar) jCB_Lugar_Final.getSelectedItem()));
            lugar.get(index).setCarre_salida(new Carretera(nombre, numero, distancia, (Lugar) jCB_Lugar_Inicio.getSelectedItem(), (Lugar) jCB_Lugar_Final.getSelectedItem()));
            lugar.get(index_2).setCarre_entrada(new Carretera(nombre, numero, distancia, (Lugar) jCB_Lugar_Inicio.getSelectedItem(), (Lugar) jCB_Lugar_Final.getSelectedItem()));
            JOptionPane.showMessageDialog(this, "Carretera ingresada exitosamente");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se guardaron los datos");
        }
        jTF_Nombre_Carre.setText("");
        jTF_Numero_Carre.setText("");
        jTF_Distancia_Carre.setText("");

    }//GEN-LAST:event_jB_Guardar_CarreMouseClicked

    private void jB_RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_RActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_RActionPerformed

    private void jB_T_RestaurantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_T_RestaurantesMouseClicked
        DefaultTreeModel m = (DefaultTreeModel) jT_Categoria.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode nodo_categoria;
        nodo_categoria = new DefaultMutableTreeNode("Categoria");
        DefaultMutableTreeNode chino;
        DefaultMutableTreeNode mexicano;
        DefaultMutableTreeNode italiano;
        DefaultMutableTreeNode comida_rapida;
        chino = new DefaultMutableTreeNode("Chino");
        mexicano = new DefaultMutableTreeNode("Mexicano");
        italiano = new DefaultMutableTreeNode("Italiano");
        comida_rapida = new DefaultMutableTreeNode("Comida Rapida");
        for (Lugar t : lugar) {
            if (t instanceof Restaurante) {
                if (((Restaurante) t).getCategoria().equalsIgnoreCase("chino")) {
                    DefaultMutableTreeNode c = new DefaultMutableTreeNode(t);
                    chino.add(c);
                } else if (((Restaurante) t).getCategoria().equalsIgnoreCase("mexicano")) {
                    DefaultMutableTreeNode me = new DefaultMutableTreeNode(t);
                    mexicano.add(me);
                } else if (((Restaurante) t).getCategoria().equalsIgnoreCase("italiano")) {
                    DefaultMutableTreeNode i = new DefaultMutableTreeNode(t);
                    italiano.add(i);
                } else if (((Restaurante) t).getCategoria().equalsIgnoreCase("comida rapida")) {
                    DefaultMutableTreeNode cr = new DefaultMutableTreeNode(t);
                    comida_rapida.add(cr);
                }
            }
        }
        nodo_categoria.add(comida_rapida);
        nodo_categoria.add(italiano);
        nodo_categoria.add(mexicano);
        nodo_categoria.add(chino);
        raiz.add(nodo_categoria);
        m.reload();

    }//GEN-LAST:event_jB_T_RestaurantesMouseClicked

    private void jB_T_CanchasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_T_CanchasMouseClicked
        DefaultTreeModel n = (DefaultTreeModel) jT_Categoria.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) n.getRoot();
        DefaultMutableTreeNode nodo_categoria;
        nodo_categoria = new DefaultMutableTreeNode("Categoria");
        DefaultMutableTreeNode football;
        DefaultMutableTreeNode basquetball;
        DefaultMutableTreeNode tennis;
        football = new DefaultMutableTreeNode("Football");
        basquetball = new DefaultMutableTreeNode("Basquetball");
        tennis = new DefaultMutableTreeNode("Tennis");
        for (Lugar t : lugar) {
            if (t instanceof Canchas) {
                if (((Canchas) t).getCategoria().equalsIgnoreCase("football")) {
                    DefaultMutableTreeNode c = new DefaultMutableTreeNode(t);
                    football.add(c);
                } else if (((Canchas) t).getCategoria().equalsIgnoreCase("basquetball")) {
                    DefaultMutableTreeNode me = new DefaultMutableTreeNode(t);
                    basquetball.add(me);
                } else if (((Canchas) t).getCategoria().equalsIgnoreCase("tennis")) {
                    DefaultMutableTreeNode i = new DefaultMutableTreeNode(t);
                    tennis.add(i);
                }
            }
        }
        nodo_categoria.add(tennis);
        nodo_categoria.add(basquetball);
        nodo_categoria.add(football);
        raiz.add(nodo_categoria);
        n.reload();
    }//GEN-LAST:event_jB_T_CanchasMouseClicked

    private void jB_RMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_RMouseClicked
        num = 1;
        DefaultTableModel modelos_2 = (DefaultTableModel) jT_Listar.getModel();
        jT_Listar.setModel(modelos_2);
        for (Lugar t : lugar) {
            if (t instanceof Restaurante) {
                Object[] newrow = {
                    t.getNombre(),
                    t.getDireccion(),
                    t.getNivel_seguridad(),
                    t.getCarre_entrada(),
                    t.getCarre_salida(),
                    ((Restaurante) t).getCategoria(),
                    ((Restaurante) t).getCalificacion()
                };
                DefaultTableModel modelos
                        = (DefaultTableModel) jT_Listar.getModel();
                modelos.addRow(newrow);
                jT_Listar.setModel(modelos);
            }

        }
    }//GEN-LAST:event_jB_RMouseClicked

    private void jB_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_CMouseClicked
        num = 2;
        String r = "";
        for (Lugar t : lugar) {
            if (t instanceof Canchas) {
                Object[] newrow = {
                    t.getNombre(),
                    t.getDireccion(),
                    t.getNivel_seguridad(),
                    t.getCarre_entrada(),
                    t.getCarre_salida(),
                    ((Canchas) t).getCategoria(),
                    r,
                    ((Canchas) t).getEstado(),};
                DefaultTableModel modelos
                        = (DefaultTableModel) jT_Listar.getModel();
                modelos.addRow(newrow);
                jT_Listar.setModel(modelos);
            }

        }
    }//GEN-LAST:event_jB_CMouseClicked

    private void jB_CaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_CaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_CaActionPerformed

    private void jB_CaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_CaMouseClicked
        num = 3;
        String r = "";
        for (Carretera t : carretera) {
            Object[] newrow = {
                t.getNombre(),
                r,
                r,
                r,
                r,
                r,
                r,
                r,
                t.getNumero(),
                t.getDistancia(),
                t.getLu_inicio(),
                t.getLu_final()
            };
            DefaultTableModel modelos
                    = (DefaultTableModel) jT_Listar.getModel();
            modelos.addRow(newrow);
            jT_Listar.setModel(modelos);

        }
    }//GEN-LAST:event_jB_CaMouseClicked
    
    private void jT_ListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_ListarMouseClicked
        if (evt.isMetaDown()) {
            jPOPM_MENU.show(jT_Listar, evt.getX(), evt.getY());

        }
    }//GEN-LAST:event_jT_ListarMouseClicked

    private void jM_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_EliminarActionPerformed
        ArrayList<Integer> t = new ArrayList();
        if (num == 1) {
            for (int i = 0; i < lugar.size(); i++) {
                if (lugar.get(i) instanceof Restaurante) {
                    t.add(i);
                }
            }
        }
        lugar.remove(t.get(jT_Listar.getSelectedRow()));
    }//GEN-LAST:event_jM_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bG_Lugar;
    private javax.swing.JButton jB_C;
    private javax.swing.JButton jB_Ca;
    private javax.swing.JButton jB_Guardar;
    private javax.swing.JButton jB_Guardar_Can;
    private javax.swing.JButton jB_Guardar_Carre;
    private javax.swing.JButton jB_Guardar_res;
    private javax.swing.JButton jB_R;
    private javax.swing.JButton jB_T_Canchas;
    private javax.swing.JButton jB_T_Restaurantes;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCB_Calificacion_Res;
    private javax.swing.JComboBox<String> jCB_Categoria_Can;
    private javax.swing.JComboBox<String> jCB_Categoria_Res;
    private javax.swing.JComboBox<String> jCB_Lugar_Final;
    private javax.swing.JComboBox<String> jCB_Lugar_Inicio;
    private javax.swing.JDialog jD_Cancha;
    private javax.swing.JDialog jD_Restaurante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jM_Eliminar;
    private javax.swing.JPopupMenu jPOPM_MENU;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRB_Cancha;
    private javax.swing.JRadioButton jRB_Casa;
    private javax.swing.JRadioButton jRB_Restaurante;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTA_Direccion;
    private javax.swing.JTextField jTF_Distancia_Carre;
    private javax.swing.JTextField jTF_Estado;
    private javax.swing.JTextField jTF_Nivel_Seguridad;
    private javax.swing.JTextField jTF_Nombre;
    private javax.swing.JTextField jTF_Nombre_Carre;
    private javax.swing.JTextField jTF_Numero_Carre;
    private javax.swing.JTabbedPane jTP_Principal;
    private javax.swing.JTree jT_Categoria;
    private javax.swing.JTable jT_Listar;
    // End of variables declaration//GEN-END:variables
    ArrayList<Lugar> lugar = new ArrayList();
    ArrayList<Carretera> carretera = new ArrayList();
    String categoria_res;
    String categoria_can;
    int calificacion;
    String estado;
    int num = 0;
    
}
